version: '2'
services:

  web:
    build:
      context: .
    depends_on:
      - redis
    links:
      - redis
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      
  redis:
    image: redis:alpine
    ports:
      - "6379"
